use_frameworks!

target 'VVCompositeButton_Example' do
  pod 'VVCompositeButton', :path => '../'

  target 'VVCompositeButton_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
